### ISSUE TITLE
Add auto-commit mode

### ISSUE THREAD

**Issue by AdrianoKF** [aai-institute/lakefs-spec#128]
For a new user of the library, having to register a hook in order to make a commit after uploading a file can be a bit daunting, since it requires understanding multiple unrelated concepts. There is also a danger of forgetting to create a commit at all, which might lead to unexpected repository states when using the library.

We currently have `client_utils.commit()`, but that involves pulling the client from a filesystem instance (and thus, does not work easily with `LakeFSFile`) and manually keeping track of repo and branch names.

Instead, we could offer a simple `auto_commit=True` option to a filesystem (or a file, as part of `close()`), which would simply create a new commit on the active branch for all modification operations (i.e., `put`, `rm`, `cp_file`). We could even harness the existing hook system for this and automatically register a `commit_file` hook for the relevant `FSEvent`s. (however, this would probably warrant a revisit of the hook system, such that multiple hooks can be registered independently for a given event to enable composability).

## Proposed API changes

- Introduce an `auto_commit: bool` argument in `LakeFSFileSystem`
- Introduce an `auto_commit: bool` argument in `LakeFSFile`

**Comment by nicholasjng** [comment]
Worth remembering that the `AbstractBufferedFile` (and thus also the `LakeFSFile`) take a boolean `autocommit` argument (https://filesystem-spec.readthedocs.io/en/latest/api.html#fsspec.spec.AbstractBufferedFile), which has a different meaning (controls auto-writing the buffer on final chunk upload) - we should think of how to name them sufficiently differently (really unfortunate naming collision tbh).

**Comment by maxmynter** [comment]
How about `commit_on_push` or `commit_on_write`?

**Comment by Maciej818** [comment]
Not needed due to introducing transaction feature.
