### ISSUE TITLE
`create_tag` on existing tag behavior

### ISSUE THREAD

**Issue by janwillemkl** [aai-institute/lakefs-spec#165]
I find the behavior of the `exists_ok` a little confusing/misleading. 

When trying to tag another commit with an already existing tag, it silently does nothing and keeps the tag on the old commit.

I expected that the tag would be updated to reference the new commit.

I guess the question here is: Are tags immutable? If so, should we set the default to `exist_ok: bool = False`? Also this function needs to get documentation.

If we consider tags mutable, we have to update the `create_tag` function.

```python

def create_tag(
    client: LakeFSClient, repository: str, ref: str | Commit, tag: str, exist_ok: bool = True
) -> Ref:
    if isinstance(ref, Commit):
        ref = ref.id
    tag_creation = TagCreation(id=tag, ref=ref)

    try:
        return client.tags_api.create_tag(repository=repository, tag_creation=tag_creation)
    except ApiException as e:
        if e.status == 409 and exist_ok:
            return client.tags_api.get_tag(repository=repository, tag=tag). # <-- This I did not expect
        raise e
```

**Comment by maxmynter** [comment]
Whether or not to allow for tag mutability depends on how we (or lakeFS) encourages to work with them.  [This](https://docs.lakefs.io/understand/model.html#tags) is their examples and description of tags:

```
Tags are a way to give a meaningful name to a specific commit. 
Using tags allow users to reference specific releases, experiments or versions by using a human friendly name.

Example tags:

v2.3 to mark a release.
dev:jane-before-v2.3-merge to mark Jane’s private temporary point.
```

We definitely want to avoid that Data Scientist B changes a tag which breaks the reproducibility of Data Scientist A's code. 

Therefore, I think it makes sense to have the tags immutable. There also exists a `delete_tag` method in the `tags_api`. Leveraging that, the reassignment is possible by deleting and subsequently creating a tag pointing to a different ref. 

This approach would make data scientists also more aware/considerate that their changes potentially break code of others. 

I will create a PR for that.
