### ISSUE TITLE
Refactor demo notebook storyline

### ISSUE THREAD

**Issue by maxmynter** [aai-institute/lakefs-spec#193]
We should define a recommended best practice of handling branches and tags to best reflect the experiments done in data science projects. 

We should then refactor the storyline of the notebook such that it reflects these recommendations. The current storyline is only written with the aim to show features of lakeFS-spec, not applicable best practices. 

If possible, we can refactor the storyline in a way such that we do not need a hidden cleanup cell to ensure idempotency of the notebook execution. 

Also align the tutorial notebook with the blog post (take good practices from the blog post) and PyData slides good practices.

**Comment by maxmynter** [comment]
Now the Repo containing the best practices is [here](https://github.com/aai-institute/data-versioning-best-practices)

**Comment by Maciej818** [comment]
@maxmynter after installing requirements.txt in a vanilla fresh env I was able to reproduce the notebook smoothly. I also like the story (it is clear and informative).

**Comment by maxmynter** [comment]
We have the other Repo and storyline finished, so it sits there if we ever need it (and should handle issues etc. there as well). The PyData presentation is a separate thing. 

So I am closing this here
