### ISSUE TITLE
Doc: How to use (fsspec) caching with lakefs-spec

### ISSUE THREAD

**Issue by Maciej818** [aai-institute/lakefs-spec#211]
### Motivation

We need to complete documentation.

### Requested solution

Add a doc: How to use (fsspec) caching with lakefs-spec.

### Acceptance Criteria (mandatory to start implementation)

- [ ] The document added to https://lakefs-spec.org 

### Definition of Done (mandatory to close an issue as completed)

- [ ] All applicable Definition of Done criteria met

**Comment by nicholasjng** [comment]
This is not in scope for us, since fsspec has a document on caching in their documentation (https://filesystem-spec.readthedocs.io/en/latest/features.html#caching-files-locally), which works agnostic of the filesystem, so we defer to them.
