### ISSUE TITLE
Doc: How to use lakefs-spec with universal-pathlib

### ISSUE THREAD

**Issue by Maciej818** [aai-institute/lakefs-spec#212]
### Motivation

Complete documentation.

### Requested solution

Add a doc: "How to use lakefs-spec with universal-pathlib".

### Acceptance Criteria (mandatory to start implementation)

- [ ] The document added to https://lakefs-spec.org 

### Definition of Done (mandatory to close an issue as completed)

- [ ] All applicable Definition of Done criteria met

**Comment by nicholasjng** [comment]
This is not in scope for us as per discussion - once there is a user request for it, we can always revisit.
