### ISSUE TITLE
Update package metadata

### ISSUE THREAD

**Issue by AdrianoKF** [aai-institute/lakefs-spec#254]
A few things in the package metadata need to be updated:

- Author email should point to an Institute mailbox (see https://github.com/aai-institute/MLOps-Engineering/issues/34)
- `Development Status` trove classifier can be moved from alpha to beta / released

**Comment by nicholasjng** [comment]
@aliabbasjaffri indicated to me that `zip-safe` is obsolete, so that can go as well.

Source: https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html#setuptools-specific-configuration (third-last table entry)
