### ISSUE TITLE
Create an integration test for `pandas` example usage

### ISSUE THREAD

**Issue by nicholasjng** [aai-institute/lakefs-spec#52]
Our `pandas` integration is so far our main example, because it showcases how `fsspec` is useful for completely abstracting away service communication from the data scientist, effectively shrinking `DataFrame` I/O to <5 lines (or even 1, with our zero-config approach).

We should make sure to write tests for it, to assert that our features work as expected. Concretely, I mean the following:

- [x] Create the test repo with sample data, so that we get the `lakes.parquet` example from which we can test `DataFrame` reads. This works by adding the `sample_data=True` option to the `RepositoryCreation` object in `conftest.ensurerepo`.
- [ ] Add a test for `pandas` parquet I/O, probably with automatic branch creation.
- [ ] Add a test with an automatic commit (I discovered that this was broken just before the demos today, fwiw - now it's fixed).

**Comment by Maciej818** [comment]
Superseded by building the tutorial notebook in CI.
